<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Resources\OrderResource\Pages;
use App\Models\Order;
use Carbon\Carbon;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\Indicator;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;

class OrderResource extends Resource
{
    protected static ?string $model = Order::class;
    protected static ?string $navigationIcon = 'heroicon-o-shopping-bag';
    protected static ?string $navigationLabel = "Buyurtmalar";

    public static function getNavigationBadge(): ?string
    {
        $user = Auth::user();
        return static::getModel()::where('source', $user->source)->count(); // TODO: Change the autogenerated stub
    }

    protected function getTableQuery(): Builder
    {
        $user = Auth::user();

        return Order::query()
            ->where('source', $user->source);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('ID_number')->label('ID')->searchable()->toggleable()->sortable(),
                TextColumn::make('createdAt')->label('Buyurtma sanasi')->sortable()->toggleable()->dateTime(),
                TextColumn::make('displayProductName')->label('Mahsulot')->searchable()->toggleable()->sortable(),
                TextColumn::make('article')->label('Artikul')->searchable()->toggleable()->sortable(),
                TextColumn::make('status')->searchable()->toggleable()->sortable()
                    ->label('Holat')
                    ->badge()
                    ->color(function (string $state): string{
                        return match ($state) {
                            'Новый' => 'warning',
                            'Принят' => 'info',
                            'Отмена' => 'danger',
                            'В пути' => 'info',
                            'Возврат' => 'gray',
                            'Выполнен' => 'success',
                            'Доставлен' => 'success',
                            'Недозвон' => 'gray',
                            default => 'null',
                        };
                    })
                    ->icon(function (string $state): ?string {
                        return match ($state) {
                            'Новый' => 'heroicon-o-sparkles',
                            'Принят' => 'heroicon-o-check-circle',
                            'Отмена' => 'heroicon-o-x-circle',
                            'В пути' => 'heroicon-o-truck',
                            'Возврат' => 'heroicon-o-x-circle',
                            'Выполнен' => 'heroicon-o-check-badge',
                            'Доставлен' => 'heroicon-o-check-badge',
                            'Недозвон' => 'heroicon-o-face-frown',
                            default => null,
                        };
                    }),
                TextColumn::make('statusUpdatedAt')->label("Oxirgi o'zgarish")->dateTime()->toggleable()->sortable(),
                TextColumn::make('source')->label('Source')->searchable()->toggleable()->sortable(),
                TextColumn::make('target')->label('Target')->money('USD', true)->searchable()->toggleable()->sortable(),
            ])->defaultSort("createdAt", 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('article')
                    ->options(Order::getAllArticleGroupedBy()->pluck('article', 'article')->toArray())
                    ->label('Artikul')
                    ->preload()
                    ->multiple()
                    ->indicator('Artikul'),
                Tables\Filters\SelectFilter::make('status')
                    ->options([
                        'Новый' => 'Новый',
                        'Принят' => 'Принят',
                        'Выполнен' => 'Выполнен',
                        'Доставлен' => 'Доставлен',
                        'Отмена' => 'Отмена',
                        'В пути' => 'В пути',
                        'Возврат' => 'Возврат',
                        'Недозвон' => 'Недозвон',
                    ])
                    ->label('Holat')
                    ->preload()
                    ->multiple()
                    ->indicator('Holat'),
                Filter::make('date_filter')
                    ->form([
                        Select::make('date_column')
                            ->label("Sana bo'yicha filterlash")
                            ->options([
                                'createdAt' => 'Buyurtma sanasi',
                                'statusUpdatedAt' => "Oxirgi o'zgarish sanasi",
                            ])
                            ->required()
                            ->reactive()
                            ->placeholder("Tanlang"),  // Make sure the user selects one
                        DatePicker::make('date_from')
                            ->label(fn (callable $get) =>
                            match ($get('date_column')) {
                                'statusUpdatedAt' => "Oxirgi o'zgarish sanasi (dan)",
                                'createdAt' => 'Buyurtma sanasi (dan)',
                                default => 'Sana (dan)',
                            }
                            )
                            ->reactive(),

                        DatePicker::make('date_until')
                            ->label(fn (callable $get) =>
                            match ($get('date_column')) {
                                'statusUpdatedAt' => "Oxirgi o'zgarish sanasi (gacha)",
                                'createdAt' => 'Buyurtma sanasi (gacha)',
                                default => 'Sana (gacha)',
                            }
                            )
                            ->reactive(),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        $column = $data['date_column'] ?? 'createdAt';  // Default to 'created_at' if nothing is selected

                        return $query
                            ->when(
                                $data['date_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate($column, '>=', $date),
                            )
                            ->when(
                                $data['date_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate($column, '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        if ($data['date_column']) {
                            $columnLabel = $data['date_column'] === 'createdAt' ? 'Buyurtma sanasi' : "Oxirgi o'zgarish";
                        } else {
                            $columnLabel = 'Buyurtma sanasi';  // Default label
                        }

                        if ($data['date_from'] ?? null) {
                            $indicators[] = Indicator::make($columnLabel . ' (dan) ' . Carbon::parse($data['date_from'])->toFormattedDateString())
                                ->removeField('date_from');
                        }

                        if ($data['date_until'] ?? null) {
                            $indicators[] = Indicator::make($columnLabel . ' (gacha) ' . Carbon::parse($data['date_until'])->toFormattedDateString())
                                ->removeField('date_until');
                        }

                        return $indicators;
                    }),
            ])
            ->actions([
//                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
//                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            // Define any relationships here
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Admin\Resources\OrderResource\Pages\ListOrders::route('/'),
            'create' => \App\Filament\Admin\Resources\OrderResource\Pages\CreateOrder::route('/create'),
            'edit' => \App\Filament\Admin\Resources\OrderResource\Pages\EditOrder::route('/{record}/edit'),
        ];
    }

}
