<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Resources\StreamResource\Pages;
use App\Filament\Resources\StreamResource\RelationManagers;
use App\Models\Landing;
use App\Models\Product;
use App\Models\Stream;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class StreamResource extends Resource
{
    protected static ?string $model = Stream::class;
    protected static ?string $navigationLabel = "Oqim";

    protected static ?string $pluralModelLabel = "Oqim";

    protected static ?string $navigationIcon = 'heroicon-o-newspaper';

    public static function getNavigationBadge(): ?string
    {

        return static::getModel()::where('source', auth()->user()->source)->count(); // TODO: Change the autogenerated stub
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('source', auth()->user()->source);
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make("stream_name")
                    ->label("Oqim nomi")
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make("product_name")
                    ->label("Mahsulot nomi")
                    ->sortable()
                    ->getStateUsing(function ($record) {
                        // Assuming $record is an instance of your Landing model and has an 'article' field
                        $landing = Landing::where('id', $record->landing_id)->first();
                        $product = Product::where('article', $landing->article)->first();

                        // Return the product name if found, otherwise return 'No Product'
                        return $product ? $product->name : 'No Product';
                    }),
                Tables\Columns\TextColumn::make("pixel_id")
                    ->label("Facebook pixel")
                    ->searchable()
                    ->sortable()
                    ->copyable()
                    ->copyMessage("Facebook Pixel Id nusxalandi"),
                Tables\Columns\TextColumn::make("full_link")
                    ->label("Oqimga link")
                    ->searchable(['link', 'full_link'])
                    ->sortable()
                    ->copyable()
                    ->copyMessage("Oqimga link nusxalandi"),
            ])
            ->defaultSort("createdAt", 'DESC')
            ->filters([
                //
            ])
            ->actions([
//                Tables\Actions\ViewAction::make()->label("Ko'rish"),
//                Tables\Actions\EditAction::make()->label("Yangilash"),
            ])
            ->bulkActions([
//                Tables\Actions\BulkActionGroup::make([
//                    Tables\Actions\DeleteBulkAction::make(),
//                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Admin\Resources\StreamResource\Pages\ListStreams::route('/'),
//            'create' => Pages\CreateStream::route('/create'),
//            'edit' => Pages\EditStream::route('/{record}/edit'),
        ];
    }


}
