<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Resources\StreamResource\Pages;
use App\Filament\Resources\StreamResource\RelationManagers;
use App\Models\Landing;
use App\Models\Product;
use App\Models\Stream;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class StreamResource extends Resource
{
    protected static ?string $model = Stream::class;
    protected static ?string $navigationLabel = "Oqim";

    protected static ?string $pluralModelLabel = "Oqim";

    protected static ?string $navigationIcon = 'heroicon-o-newspaper';

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count(); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
//                Grid::make(2)
//                    ->schema([
//                        Section::make([
//                            Select::make('article')
//                                ->label('Artikul')
//                                ->options(Product::getAllArticleGroupedBy()->pluck('article', 'article')->toArray())
//                                ->searchable()
//                                ->preload()
//                                ->reactive()
//                                ->afterStateUpdated(function ($state, Set $set) {
//                                    if ($state) {
//                                        $product = Product::where('article', $state)->first();
//                                        if ($product) {
//                                            $set('product_id', $product->id);
//                                            $set('article', $product->article);
//                                            $set('buyPrice', $product->buyPrice);
//                                            $set('bonus', $product->bonus);
//                                            $set('name', $product->name);
//                                        }
//                                        $landing = Landing::where('article', $state)->first();
//                                        if ($landing){
//                                            $set('landing_id', $landing->id);
//                                            $set('title', $landing->title);
//                                            $set('img1', $landing->img1);
//                                        }
//                                    }
//                                })
//                                ->afterStateHydrated(function ($state, Set $set) {
//                                    if ($state) {
//                                        $product = Product::where('article', $state)->first();
//                                        if ($product) {
//                                            $set('product_id', $product->id);
//                                            $set('article', $product->article);
//                                            $set('buyPrice', $product->buyPrice);
//                                            $set('bonus', $product->bonus);
//                                            $set('name', $product->name);
//                                        }
//                                        $landing = Landing::where('article', $state)->first();
//                                        if ($landing){
//                                            $set('landing_id', $landing->id);
//                                            $set('title', $landing->title);
//                                            $set('img1', $landing->img1);
//                                        }
//                                    }
//                                }),
//
//                            Section::make([
//                                TextInput::make('name')
//                                    ->label('Mahsulot nomi')
//                                    ->readOnly(),
//                                TextInput::make('buyPrice')
//                                    ->label('Sotuv narxi:')
//                                    ->formatStateUsing(function ($state) {
//                                        return number_format($state, 0, '.', ' ');
//                                    })
//                                    ->readOnly(),
//                                Forms\Components\Textarea::make('title')
//                                    ->label('Title:')
//                                    ->readOnly(),
//                                TextInput::make('bonus')
//                                    ->label('Bonus: 2+1')
//                                    ->disabled(),
////
//                                Hidden::make('product_id')->default(null),
//                                Hidden::make('landing_id')->default(null),
//                                Hidden::make('article')->default(null),
//                            ])->columnSpanFull(),
//                        ])->columnSpan(1),
//
//                        Section::make([
////                            FileUpload::make("img1")
////                                ->label("Rassim")
////                                ->disk('public')
////                                ->directory('landing_images'),
//                            TextInput::make('link')
//                                ->label('Oqim nomi')
//                                ->placeholder('Value')
//                                ->readOnly(),
//                            TextInput::make('pixel_id')
//                                ->label('Facebook pixel')
//                                ->placeholder('Value'),
//                            TextInput::make('full_link')
//                                ->label('Yaratilgan oqimga link')
//                                ->placeholder('Value')
//                                ->readOnly(),
//                        ])->columnSpan(1),
//                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make("name")
                    ->label("Oqim nomi")
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make("product_name")
                    ->label("Mahsulot nomi")
                    ->sortable()
                    ->getStateUsing(function ($record) {
                        // Assuming $record is an instance of your Landing model and has an 'article' field
                        $landing = Landing::where('id', $record->landing_id)->first();
                        $product = Product::where('article', $landing->article)->first();

                        // Return the product name if found, otherwise return 'No Product'
                        return $product ? $product->name : 'No Product';
                    }),
                Tables\Columns\TextColumn::make("pixel_id")
                    ->label("Facebook pixel")
                    ->searchable()
                    ->sortable()
                    ->copyable()
                    ->copyMessage("Facebook Pixel Id nusxalandi"),
                Tables\Columns\TextColumn::make("full_link")
                    ->label("Oqimga link")
                    ->searchable()
                    ->sortable()
                    ->copyable()
                    ->copyMessage("Oqimga link nusxalandi"),
            ])
            ->defaultSort("created_at", 'DESC')
            ->filters([
                //
            ])
            ->actions([
//                Tables\Actions\ViewAction::make()->label("Ko'rish"),
//                Tables\Actions\EditAction::make()->label("Yangilash"),
            ])
            ->bulkActions([
//                Tables\Actions\BulkActionGroup::make([
//                    Tables\Actions\DeleteBulkAction::make(),
//                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Admin\Resources\StreamResource\Pages\ListStreams::route('/'),
//            'create' => Pages\CreateStream::route('/create'),
//            'edit' => Pages\EditStream::route('/{record}/edit'),
        ];
    }


}
