<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\TransactionResource\Pages\ListTransactions;
use App\Filament\Admin\Resources\TransactionResource\Widgets\TransactionOverview;
use App\Models\Transaction;
use Carbon\Carbon;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\Indicator;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class TransactionResource extends Resource
{
    protected static ?string $model = Transaction::class;

    protected static ?string $navigationIcon = 'heroicon-o-currency-dollar';
    protected static ?string $recordTitleAttribute = "description";

    protected static ?string $navigationLabel = "Moliya";

    protected static ?string $pluralModelLabel = "Moliya";

    protected static ?int $navigationSort = 3;
    public static function getGloballySearchableAttributes(): array
    {
        return ['amount', 'date', 'description']; // TODO: Change the autogenerated stub
    }
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::where('contractor_name', auth()->user()->source)->count(); // TODO: Change the autogenerated stub
    }
    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('contractor_name', auth()->user()->source);
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
            ]);

    }
    public static function table(Table $table): Table
    {

        return $table
            ->columns([
                TextColumn::make('transaction_date')
                    ->label('Sana')
                    ->date()
                    ->sortable(),
                TextColumn::make('amount')
                    ->label('Summa')
                    ->sortable()
                    ->searchable()
                    ->formatStateUsing(function ($state) {
                        // Format the state as a number with space as thousand separator
                        $formattedState = number_format($state, 0, '.', ' ');

                        // Return the formatted state with the prefix in bold
                        return $formattedState;
                    }),
                TextColumn::make('description')
                    ->label('Izoh')
                    ->sortable()
                    ->searchable(),
            ])
            ->paginated([
                10,
                15,
                25,
                40,
                50,
                100,
            ])
            ->filters([
                Filter::make('transaction_date')
                    ->form([
                        DatePicker::make('created_from')->label("Tranzaksiya sana (dan)"),
                        DatePicker::make('created_until')->label("Tranzaksiya sana (gacha)"),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('transaction_date', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('transaction_date', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        $columnLabel = 'Tranzaksiya sanasi';  // Default label

                        if ($data['created_from'] ?? null) {
                            $indicators[] = Indicator::make($columnLabel . ' (dan) ' . Carbon::parse($data['created_from'])->toFormattedDateString())
                                ->removeField('created_from');
                        }

                        if ($data['created_until'] ?? null) {
                            $indicators[] = Indicator::make($columnLabel . ' (gacha) ' . Carbon::parse($data['created_until'])->toFormattedDateString())
                                ->removeField('created_until');
                        }

                        return $indicators;
                    }),
            ])
            ->actions([
            ]);

    }

    public static function getWidgets(): array
    {
        return [
            TransactionOverview::class,
        ]; // TODO: Change the autogenerated stub
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListTransactions::route('/'),
        ];
    }
}
