<?php

namespace App\Filament\Landing\Resources\CreativeResource\Pages;

use App\Filament\Landing\Resources\CreativeResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateCreative extends CreateRecord
{
    protected static string $resource = CreativeResource::class;

    protected static ?string $title = "Kreativ qo'shish";
    protected function getCreatedNotification(): ?Notification
    {
        return Notification::make()
                ->success()
                ->title("Kreativ qo'shildi")
                ->body("Kreativ muvaffaqiyatli qo'shildi.");    // TODO: Change the autogenerated stub
    }

}
