<?php

namespace App\Filament\Landing\Resources\CreativeResource\Pages;

use App\Filament\Landing\Resources\CreativeResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;

class EditCreative extends EditRecord
{
    protected static string $resource = CreativeResource::class;

    protected static ?string $title = 'Kreativni Tahrirlash';

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getSavedNotification(): ?Notification
    {
        return Notification::make()
            ->success()
            ->title("Kreativ yangilandi")
            ->body("Kreativ muvaffaqiyatli yangilandi."); // TODO: Change the autogenerated stub
    }

}
